# version 5.20
system:
  debug: True
  greet_new_members: True
  manage_game_roles: True
  show_unknown_command: True
  language: fr_FR # only fr_FR is supported right now

paths: # can be left as default values
  tournoi: data/tournoi.json
  participants: data/participants.json
  stream: data/stream.json
  ranking: data/ranking.csv
  gamelist: config/gamelist.yml
  auto_mode: config/auto_mode.yml
  preferences: config/preferences.yml

discord:
  secret:
  guild:
  prefix:
  channels:
    blabla:
    annonce:
    check_in:
    inscriptions:
    scores:
    stream:
    queue:
    tournoi:
    deroulement:
    faq:
    resultats:
    roles:
    to:
  categories:
    tournoi:
  roles:
    challenger:
    to:
    streamer:
  emojis:
    logo:

challonge:
  user:
  api_key:
